Objetivo 1
joaquingv12/Proyecto-IV pull request #5
Opened 2021-09-24 11:50 UTC by joaquingv12

2021-09-25 08:04 UTC, JJ approved these changes
Coincidencia de errores (como una forma determinada de titular las historias de usuario) es el tipo de cosas que apuntan a plagio o a trabajo en colaboración y que, si bien no son todavía una bandera roja, si se repiten y son más flagrantes pueden causar la no superación del objetivo y, en el futuro, la asignatura. Por favor, tratad de superar el objetivo individualmene, y si ha habido inspiración mutua y/o colaboración decirlo desde el principio es lo único aceptable.
Por lo demás, mismos errores
1. No existe un problema a resolver, por lo que las diferentes "historias de usuario" son palos de ciego que no contribuyen a la comprensión del problema ni a resolución.
2. Los títulos de las historias de usuario, aparte de ser la coincidencia de la que se habla más arriba, deben de ser una descripción sucinta de qué es lo que el usuario desea.
3. Las historias de usuario son, como en el caso con el que coinciden el típo de títulos, "user journeys" que incluyen diferentes características. Como en ese caso también, no contribuyen a la comprensión, ni siquiera a la caracterización del problema.

En general, las historias de usuario creadas no contribuyen a ser una guía por la que el equipo de desarrollo pueda empezar a implementar. 
Los milestones tampoco son productos mínimamente viables. Por favor, consulta de nuevo toda la literatura sobre el tema: descripción de la clas,e presentaciones, etcétera. En general, esto es siempre una mejor estrategia que juntarse con otra persona o personas y decidir conjuntamente qué se va a hacer para acabar entregando cosas más o menos con el mismo grado bajo de consecución de los objetivos.

2021-09-25 11:18 UTC, joaquingv12 commented
De acuerdo, acabo de modificar los issues y los milestones.

2021-09-26 07:25 UTC, JJ commented
> De acuerdo, acabo de modificar los issues y los milestones.

Creo que no has entendido el punto 1 al 3. Tienes que cambiar la descripción al problema, de forma que represente un verdadero problema a resolver. Tienes que crear una serie de perfiles de usuario como indica en el guión del objetivo. Finalmente, revisa el material sobre qué constituye un milestone, es decir, un producto mínimamente viable. "Agricultores" no parece la descripción de uno de ellos.

2021-09-26 19:17 UTC, joaquingv12 commented
Listo para revisión.

2021-09-27 16:43 UTC, JJ requested changes
Por favor, consulta el material de clase y el que puedas encontrar en la web para entender
* Qué es una historia de usuario
* Qué es la lógica de negocio.
* Qué es un hito/milestone/producto mínimamente viable. Pasado mañana daré un taller sobre el tema.

2021-09-27 16:43 UTC, JJ commented on README.md
> +* [HUagricultor](https://github.com/joaquingv12/Proyecto-IV/issues/3)
Las historias de usuario no tienen nombre de persona, eso creo que os lo dejé claro.

2021-09-27 16:43 UTC, JJ commented on docs/perfil_usuarios.md
> +* **Luis Sánchez Fernández**: Tiene 38 años y es el director de la empresa Frutas S.L, empresa que está creciendo en la provincia de Granada. Tiene una gran experiencia manejando ordenadores y móvile
¿Zona elegida? ¿Es una aplicación inmobiliaria?

2021-09-29 16:52 UTC, joaquingv12 commented
Listo para revisión.

2021-09-30 05:35 UTC, JJ requested changes
Ninguno de los tres hitos es un producto mínimamente viable, ni está descrito como tal. De hecho, es complicado sin tener clara la lógica de negocio describir qué PMVs van a crearse en su desarrollo.

2021-09-30 05:35 UTC, JJ commented on README.md
> +La idea de este proyecto es crear un sistema de ayuda a los agricultores, aportándoles ayuda sobre sus cosechas, aviśandoles sobre periodos de cosecha, polinización, etc. Además, podrán calcular sus
¿Qué lógica de negocio tiene calcular las ganancias aparte de sumar? ¿En base a qué se van a predecir? ¿Tienes claro que el algoritmo para predecir lo tienes que hacer tú?

2021-09-30 05:35 UTC, JJ commented on README.md
> +* Beneficios que le aportará
¿Qué lógica de negocio aporta esto?

2021-09-30 05:35 UTC, JJ commented on README.md
> +También será útil para aquellas personas que llevan varios años trabajando en la agricultura pero no obtienen los beneficios que esperaban, ¿será que no estoy recolectando los frutos en la fecha ópti
¿Qué valor añade a la búsqueda en google de "Mejor fecha para polinizar x"? ¿Y qué lógica de negocio da buscar los frutos que se cultivan en la zona?

2021-10-01 05:51 UTC, JJ requested changes

2021-10-01 05:51 UTC, JJ commented on README.md
> +
Has cambiado esto, pero no los personajes ni las historias de usuario. Por favor, cuando lo hagas márcalo como listo para revisión.

2021-10-01 20:25 UTC, joaquingv12 commented
He editado las historias de usuario y los milestones con la nueva idea, además de cambiar el perfil de los usuarios. Listo para revisión.

2021-10-02 06:47 UTC, JJ requested changes
Por favor consulta el concepto de milestone. Son hitos en la elaboración de un proyecto. Si el milestone 1 no tiene ninguna historia de usuario asociada, ¿cómo va a alcanzarse?
Por otro lado, los hitos tampoco son productos mínimamente viables. Consulta el concepto, y aplícalo a la descripción de los hitos.

2021-10-02 10:30 UTC, joaquingv12 commented
Listo para revisión.

2021-10-02 15:37 UTC, JJ approved these changes
Los milestones todavía no son muy realistas (por ejemplo, un módulo con un ¿archivo?) y especialmente el problema es que no parece que se acabe de asimilar el concepto de que *realmente* hay que hacer esa lógica de negocio. El siguiente objetivo lo hará @jesusmarzor.

2021-10-03 08:27 UTC, merged